name: ci
on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - name: Install packages via packages.json
        run: make install
      - name: Lint
        run: make lint
      - name: Format check
        run: make format_check
